version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: autos
      POSTGRES_USER: autos
      POSTGRES_PASSWORD: autos
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/autos
      DATABASE_USERNAME: autos
      DATABASE_PASSWORD: autos
      APP_SEED: "true"
      APP_SEED_RESET: "false"
    ports:
      - "8080:8080"
volumes:
  dbdata:
